### PR TITLE
Update structure to match new taitan

### LINKED ISSUE #358: [Feature request] direct link between english and swedish sites
Hey @whoever reads this :)

tl;dr: clicking the "english" or "svenska"-button should redirect to the same page, i.e. clicking "english" on an article should lead to the same article in english (if it exists). Note that this is a feature-request, not a bug or complaint :)

first of all, it is really nice that a lot of content on the website is available in english.
However I still usually browse the swedish version (it is good to learn the swedish terms, and sometimes it at least feels more reliable to look at the swedish version) - and if I don't understand something I then intuitively click on the "English" button, before realizing that I have to find the same page again. This is at least at the beginning a bit confusing, as the top "navigation bar" looks different in english and swedish (which is not bad in itself, because the targeted audience is slightly different). 
I can make changes myself as pull request, however the question I would ask people who have previously worked on the webpage is:
- is it possible to change the "switch language" behavior without substantial changes to the architecture?

Other suggestions that improve the website (could be opened as different issues if one feels the need for that):
- show a navigation path at the top of the page (to the right of "Tillbaka" or something)
- prefix translated (english) pages titles with [EN] automatically, at least in the search bar. This avoids confusion while using the search (see picture).

grafik

### PR DESCRIPTION
**Pull request by Herkarl**
Merge together with [taitan#33](https://github.com/datasektionen/taitan/pull/33), and [bawang#78](https://github.com/datasektionen/bawang/pull/78). These will be undrafted once everything is ready. 

Fixes #358

Sidenote: While doing this, I noticed `sektionen/krisplaner` doesn't have an English page.

## Describe your changes

Updates the structure of the repo to match the new language features of taitan (see [taitan#33](https://github.com/datasektionen/taitan/pull/33)). 
It does this by creating separate `body_sv.md` and `body_en.md` instead of `body.md`, and having them in the same folder (and the same for `siderbar`, and adding `Title_sv` and `Title_en` in `meta.toml`).

Advantages:
- Much easier to cleanly link between the Swedish and English versions of pages
- Makes it harder for different languages to become out of sync: 
  - Easier to remember to update all languages for a page in one go
  - Forces the structure of the English and Swedish version of the site to be exactly the same 

Neutral:
- Same path for English and Swedish page (could be nice to have it localized, it is harder for English speaking people to remember the paths)

Negative:
- All old English links dies. (Or it has to be added to the jumpfile. I haven't done this since it felt like clogging up the jumpfile. But it would in line with how we've done similar stuff previously)

## Checklist before requesting a review

- [x] I have performed a self-review of my changes
  - Instructions for easily viewing your changes locally is available in [the readme](https://github.com/datasektionen/bawang-content?tab=readme-ov-file#k%C3%B6ra-lokalt).
- [x] I have updated both Swedish and English pages (if not motivate why)

### CODE REVIEW

**Comment by Benjaneb** [comment]
Love this change! Though it's annoying for internationals to read Swedish URLs I doubt it's really a problem since I believe it's very few that actually try to memorize URLs to subpages.

**Review by Benjaneb — DISMISSED** [review]

**Review by foodelevator — DISMISSED** [review]
Stacken är den verkligen uppe???

I guess you could discuss if the path names should be en English or Swedish, not sure if much has been said there. I don't really know what I think about that though, so I'm happy with the choice you made :)

**Comment by Herkarl** [comment]
> Stacken är den verkligen uppe???

Took the chance to clean up some unused stuff ;)
 
> I guess you could discuss if the path names should be en English or Swedish, not sure if much has been said there. I don't really know what I think about that though, so I'm happy with the choice you made :)

My choice was mostly due to us being an Swedish first organization (like it's our operational language e.t.c.), so we can basically always be sure that the Swedish version of a page exists, which isn't really true for any other langugage. Another reason I thought of now is that there are many terms that we don't really have a perfect translation for. 

I suppose the main reason for having it in English would be so that we don't have to care about åäö.

**Review by foodelevator — CHANGES_REQUESTED** [review]
```
$ find -name 'body_*.md' -size 0
./naringsliv/metaspexet/body_en.md
./naringsliv/mottagningen/body_en.md
```
these ones should probably be removed since they're empty.

Other than that we should be ready to merge!

**Comment by Herkarl** [comment]
Agree! Then it is consistent how we handle non-existing english pages! I checked that the sidebars were empty as well.

**Review by foodelevator — APPROVED** [review]

**Pull request merged**
