### PR TITLE
Update operational plans

### PR DESCRIPTION
**Pull request by psoder**
## Describe your changes

Add dJubileet 2023s plan and move all plans to the project page.

## Checklist before requesting a review

- [x] I have performed a self-review of my changes
- [x] I have updated both Swedish and English pages (if not motivate why)

### CODE REVIEW

**Comment by Herkarl** [comment]
I'm not convinced that the project's verksamhetsplaner shouldn't be available on the same page as the ordinary verksamhetplan, since hold the same formal status. 

Great idea to include them with the list of projects though :+1:

**Comment by psoder** [comment]
I don't agree that they should be grouped together with the Chapters operational plans. In my experience people go to [verksamt.datasektionen.se](https://verksamt.datasektionen.se/) for those plans. 

With that said I think this is a much larger issue, i.e. the website needs some love and attention. The more I think about it the more I'm starting to believe that we should only have a link to the D-rek document in order to minimize the risk of the list becoming outdated. There's not really a point in maintaining multiple lists.

For the time being I think that the best solution would be to put information not on [datasektionen.se](https://datasektionen.se/)

**Comment by psoder** [comment]
On a side note I think that we should upload the operational plans (and other similar documents) to Drive instead of yoggi. 

Having everything on a shared Drive (maybe "Bra att ha saker"?) would still allow you to share a link to the pdf but it would make it more easily accessible for the common man.

**Review by abhisas — COMMENTED** [review]
Personally I think all the operational plans should be as easily accessible as possible since I think a big reason is to why people forget about them is that they are not very intuitive to navigate and find. But, as Pontus said, this seems like a bigger issue and linking it to the drive document seems like a good fix for the time being.

**Comment by psoder** [comment]
So what are we thinking @datasektionen/d-rektoratet? Should the operational plans for the projects be with the list of projects or should they be together with the chapters operational plans?

I strongly believe they should be in the project list. 

If no one else has strong contradicting opinions I think it's time to merge.

**Comment by Herkarl** [comment]
I still think that there should be a link to the project page from the verksamhetsplan-page, i.e something akin to:

```
Verksamhetsplaner för projekt är listat tillsammans med projekten på [datasektionen.se/namnder](https://datasektionen.se/namnder). 
```

Mind you that this is purely to make the user experience more friendly, since it's not that unlikely nor unreasonable that someone might go to the **verksamhetplan** page to look for a _verksamhetplan_ for a project.

**Review by Herkarl — APPROVED** [review]

**Pull request merged**
